---
services:
  otel-collector:
    env_file: ./.env
    image: otel/opentelemetry-collector-contrib
    ports:
      - 1888:1888 # pprof
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 8888:8888 # Prometheus metrics exposed by collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 55679:55679 # zpages extension
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
